# Generated by Django 5.2.5 on 2025-08-25 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('time_duration', models.PositiveIntegerField()),
                ('is_done', models.BooleanField(default=True)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('habit_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_reminded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
        migrations.CreateModel(
            name='MotivationPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фразы',
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
            ],
            options={
                'verbose_name': 'Трекер',
                'verbose_name_plural': 'Трекеры',
            },
        ),
    ]
